### ISSUE TITLE
subscribe returns string instead of object

### ISSUE THREAD

**Issue by shripadk** [bnoguchi/redis-node#3]
Here is the scenario. client1 : publisher, client2 : subscriber

```
client1.publish('channel-1', { a: "a", b: "b" });

client2.subscribeTo('channel-1', function(channel, message) {
console.log(message); // returns '[Object object]' string rather than an object!!!
});
```

I thought of stringifying the object into JSON while publishing and parsing it on subscription. That does not work as it becomes cyclic. (the source is already converting it into an object). How should i parse it on the subscriber side?

**Comment by bnoguchi** [comment]
Use JSON.stringify when publishing and JSON.parse on the subsribeTo callback message argument. See http://github.com/bnoguchi/redis-node/commit/648d28e08e82e7660cda34308177676d24470e80 which is an updated PubSub test in the test suite that shows how to use PubSub with JSON.
