### ISSUE TITLE
Data gets corrupted if it contains special chars.

### ISSUE THREAD

**Issue by mape** [bnoguchi/redis-node#5]
I'm trying to save JSON strings in redis using redis-node but when the string contains å ä or ö it gets corrupted and can't be parsed.

Example is located here: https://gist.github.com/665446

**Comment by bnoguchi** [comment]
See my comment in your gist you provided above.

To summarize:

The way to deal with special characters is the following:
    var buf = new Buffer(32),
          size = buf.write(specialChars, 0, "utf8");
    specialChars = buf.slice(0, size);

I think testing for multi-byte characters on all incoming data to the libraray from INSIDE redis-node will sacrifice speed/performance.  Therefore, it might be better for each user to determine the intent of the input string/buffer and act accordingly.

Your thoughts?

**Comment by mape** [comment]
Thanks for providing a possible fix, I've opted to move to https://github.com/mranney/node_redis though, as that implementation does what I need natively.
