### ISSUE TITLE
Out of bounds unexpected.

### ISSUE THREAD

**Issue by zephyrus** [bnoguchi/redis-node#7]
hi Brian

every message on subscribed chanel by pattern(psubscribe) i get following exception:

/lib/replies/multibulkReply.js:146
        throw "Out of bounds unexpected.";
        ^
Out of bounds unexpected.

could you fix this?

(node 0.3.1 + redis 2.0.4)

**Comment by bnoguchi** [comment]
Can you send me a gist or submit a failing test? I'll take a look at it later today.

**Comment by zephyrus** [comment]
test file:

var r = require("./lib/redis").createClient();

r.subscribeTo('*', function(){
    console.log(arguments)
})

and command from console to reproduce
redis-cli publish test a

**Comment by bnoguchi** [comment]
Thanks for uncovering this.  Just pushed a fix.
