### ISSUE TITLE
Multiple concurrent requests get out-of-order responses?

### ISSUE THREAD

**Issue by rjp** [bnoguchi/redis-node#8]
I've got a connect HTTP server using redis-node which works fine until you ramp up concurrency - then redis lookups start returning out of order answers (ie an SCARD will return "Fish" because the previous command was a GET.)

Installed is commit ce4f55a8.

I'm not sure how to supply a helpful test or anything like that - the problem is intermittent. I can supply tcpdumps or proxy traces of the traffic to/from redis if those help.

**Comment by bnoguchi** [comment]
What's your concurrency setup?

**Comment by rjp** [comment]
There isn't a specific one that I'm aware of. It's just a connect server being tested with "ab -n 5000 -c 20 URL". Works fine until you get to about -n 10, then it starts breaking.

**Comment by bnoguchi** [comment]
Pushed a fix.
